name: Deploy Quiz App to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload static files
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./  # Deploy root folder (your HTML, CSS, JS files)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

